/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_capteur (void)
{
  GtkWidget *gestion_capteur;
  GtkWidget *fixed1;
  GtkWidget *rechercher_caop;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label32;
  GtkWidget *modifier_cap;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label31;
  GtkWidget *defectueux_cap;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label33;
  GtkWidget *afficher_cap;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label30;
  GtkWidget *label34;
  GtkWidget *ajout_cap;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label39;
  GtkWidget *image16;
  GtkWidget *image17;

  gestion_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_capteur), _("Gestion des capteurs"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_capteur), fixed1);

  rechercher_caop = gtk_button_new ();
  gtk_widget_show (rechercher_caop);
  gtk_fixed_put (GTK_FIXED (fixed1), rechercher_caop, 304, 280);
  gtk_widget_set_size_request (rechercher_caop, 200, 60);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (rechercher_caop), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\">Chercher</span></b>"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox8), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  modifier_cap = gtk_button_new ();
  gtk_widget_show (modifier_cap);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier_cap, 304, 368);
  gtk_widget_set_size_request (modifier_cap, 200, 60);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (modifier_cap), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Modifier</span></b>"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox7), label31, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  defectueux_cap = gtk_button_new ();
  gtk_widget_show (defectueux_cap);
  gtk_fixed_put (GTK_FIXED (fixed1), defectueux_cap, 304, 464);
  gtk_widget_set_size_request (defectueux_cap, 200, 60);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (defectueux_cap), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Capteurs defectueux"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox9), label33, FALSE, FALSE, 0);

  afficher_cap = gtk_button_new ();
  gtk_widget_show (afficher_cap);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_cap, 304, 184);
  gtk_widget_set_size_request (afficher_cap, 200, 60);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (afficher_cap), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("<b><span color=\"orange\">Afficher</span></b>"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label34 = gtk_label_new (_("<b><span color=\"Darkred\">Gestion des capteurs</span></b>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed1), label34, 288, 40);
  gtk_widget_set_size_request (label34, 216, 33);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  ajout_cap = gtk_button_new ();
  gtk_widget_show (ajout_cap);
  gtk_fixed_put (GTK_FIXED (fixed1), ajout_cap, 304, 104);
  gtk_widget_set_size_request (ajout_cap, 200, 60);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (ajout_cap), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\">Ajouter</span></b>"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox14), label39, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  image16 = create_pixmap (gestion_capteur, "images.jfif");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed1), image16, 640, 416);
  gtk_widget_set_size_request (image16, 157, 157);

  image17 = create_pixmap (gestion_capteur, "téléchargé.jfif");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed1), image17, 32, 432);
  gtk_widget_set_size_request (image17, 104, 136);

  g_signal_connect ((gpointer) rechercher_caop, "clicked",
                    G_CALLBACK (on_rechercher_caop_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_cap, "clicked",
                    G_CALLBACK (on_modifier_cap_clicked),
                    NULL);
  g_signal_connect ((gpointer) defectueux_cap, "clicked",
                    G_CALLBACK (on_defectueux_cap_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_cap, "clicked",
                    G_CALLBACK (on_afficher_cap_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajout_cap, "clicked",
                    G_CALLBACK (on_ajout_cap_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_capteur, gestion_capteur, "gestion_capteur");
  GLADE_HOOKUP_OBJECT (gestion_capteur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_capteur, rechercher_caop, "rechercher_caop");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion_capteur, modifier_cap, "modifier_cap");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label31, "label31");
  GLADE_HOOKUP_OBJECT (gestion_capteur, defectueux_cap, "defectueux_cap");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_capteur, afficher_cap, "afficher_cap");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion_capteur, ajout_cap, "ajout_cap");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label39, "label39");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image17, "image17");

  return gestion_capteur;
}

GtkWidget*
create_aj_capteur (void)
{
  GtkWidget *aj_capteur;
  GtkWidget *fixed2;
  GtkObject *aj1_adj;
  GtkWidget *aj1;
  GtkObject *aj2_adj;
  GtkWidget *aj2;
  GtkWidget *ajc;
  GtkObject *aj3_adj;
  GtkWidget *aj3;
  GtkWidget *retour1;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label35;
  GtkWidget *aj4;
  GtkWidget *label6;
  GtkWidget *ajA;
  GSList *ajA_group = NULL;
  GtkWidget *ajB;
  GtkWidget *ajC;
  GtkWidget *label5;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label7;
  GtkWidget *label4;
  GtkWidget *button_aj;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label40;
  GtkWidget *label41;

  aj_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (aj_capteur), _("Ajouter un capteur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (aj_capteur), fixed2);

  aj1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  aj1 = gtk_spin_button_new (GTK_ADJUSTMENT (aj1_adj), 1, 0);
  gtk_widget_show (aj1);
  gtk_fixed_put (GTK_FIXED (fixed2), aj1, 216, 184);
  gtk_widget_set_size_request (aj1, 60, 27);

  aj2_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  aj2 = gtk_spin_button_new (GTK_ADJUSTMENT (aj2_adj), 1, 0);
  gtk_widget_show (aj2);
  gtk_fixed_put (GTK_FIXED (fixed2), aj2, 480, 184);
  gtk_widget_set_size_request (aj2, 60, 27);

  ajc = gtk_calendar_new ();
  gtk_widget_show (ajc);
  gtk_fixed_put (GTK_FIXED (fixed2), ajc, 192, 248);
  gtk_widget_set_size_request (ajc, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (ajc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  aj3_adj = gtk_adjustment_new (1, 0, 24, 1, 10, 10);
  aj3 = gtk_spin_button_new (GTK_ADJUSTMENT (aj3_adj), 1, 0);
  gtk_widget_show (aj3);
  gtk_fixed_put (GTK_FIXED (fixed2), aj3, 480, 288);
  gtk_widget_set_size_request (aj3, 60, 27);

  retour1 = gtk_button_new ();
  gtk_widget_show (retour1);
  gtk_fixed_put (GTK_FIXED (fixed2), retour1, 72, 744);
  gtk_widget_set_size_request (retour1, 88, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (retour1), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("<b><span color=\"Red\">Retour</span></b>"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  aj4 = gtk_combo_box_new_text ();
  gtk_widget_show (aj4);
  gtk_fixed_put (GTK_FIXED (fixed2), aj4, 248, 576);
  gtk_widget_set_size_request (aj4, 216, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Rez_de_chaussee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("1_er_etage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("2_eme_etage"));

  label6 = gtk_label_new (_("<b><span color=\"darkblue\">Etage:</span></b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 160, 584);
  gtk_widget_set_size_request (label6, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  ajA = gtk_radio_button_new_with_mnemonic (NULL, _("Debit"));
  gtk_widget_show (ajA);
  gtk_fixed_put (GTK_FIXED (fixed2), ajA, 192, 488);
  gtk_widget_set_size_request (ajA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajA), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajA));

  ajB = gtk_radio_button_new_with_mnemonic (NULL, _("Dechet"));
  gtk_widget_show (ajB);
  gtk_fixed_put (GTK_FIXED (fixed2), ajB, 312, 488);
  gtk_widget_set_size_request (ajB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajB), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajB));

  ajC = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (ajC);
  gtk_fixed_put (GTK_FIXED (fixed2), ajC, 440, 488);
  gtk_widget_set_size_request (ajC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajC), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajC));

  label5 = gtk_label_new (_("<b><span color=\"darkblue\">Heure:</span></b>"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 376, 296);
  gtk_widget_set_size_request (label5, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label2 = gtk_label_new (_("<b><span color=\"darkblue\">ID:</span></b>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 128, 192);
  gtk_widget_set_size_request (label2, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label3 = gtk_label_new (_("<b><span color=\"darkblue\">Valeur:</span></b>"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 376, 192);
  gtk_widget_set_size_request (label3, 64, 17);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  label7 = gtk_label_new (_("<b><span color=\"darkblue\">Type:</span></b>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 112, 488);
  gtk_widget_set_size_request (label7, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label4 = gtk_label_new (_("<b><span color=\"darkblue\">Date:</span></b>"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 112, 288);
  gtk_widget_set_size_request (label4, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  button_aj = gtk_button_new ();
  gtk_widget_show (button_aj);
  gtk_fixed_put (GTK_FIXED (fixed2), button_aj, 272, 688);
  gtk_widget_set_size_request (button_aj, 104, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_aj), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\">Ajouter</span></b>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox15), label40, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  label41 = gtk_label_new (_("<b><span color=\"darkgreen\">Ajout d'un capteur</span></b>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed2), label41, 168, 48);
  gtk_widget_set_size_request (label41, 336, 41);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  g_signal_connect ((gpointer) retour1, "clicked",
                    G_CALLBACK (on_retour1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aj, "clicked",
                    G_CALLBACK (on_button_aj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aj_capteur, aj_capteur, "aj_capteur");
  GLADE_HOOKUP_OBJECT (aj_capteur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (aj_capteur, aj1, "aj1");
  GLADE_HOOKUP_OBJECT (aj_capteur, aj2, "aj2");
  GLADE_HOOKUP_OBJECT (aj_capteur, ajc, "ajc");
  GLADE_HOOKUP_OBJECT (aj_capteur, aj3, "aj3");
  GLADE_HOOKUP_OBJECT (aj_capteur, retour1, "retour1");
  GLADE_HOOKUP_OBJECT (aj_capteur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (aj_capteur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (aj_capteur, image10, "image10");
  GLADE_HOOKUP_OBJECT (aj_capteur, label35, "label35");
  GLADE_HOOKUP_OBJECT (aj_capteur, aj4, "aj4");
  GLADE_HOOKUP_OBJECT (aj_capteur, label6, "label6");
  GLADE_HOOKUP_OBJECT (aj_capteur, ajA, "ajA");
  GLADE_HOOKUP_OBJECT (aj_capteur, ajB, "ajB");
  GLADE_HOOKUP_OBJECT (aj_capteur, ajC, "ajC");
  GLADE_HOOKUP_OBJECT (aj_capteur, label5, "label5");
  GLADE_HOOKUP_OBJECT (aj_capteur, label2, "label2");
  GLADE_HOOKUP_OBJECT (aj_capteur, label3, "label3");
  GLADE_HOOKUP_OBJECT (aj_capteur, label7, "label7");
  GLADE_HOOKUP_OBJECT (aj_capteur, label4, "label4");
  GLADE_HOOKUP_OBJECT (aj_capteur, button_aj, "button_aj");
  GLADE_HOOKUP_OBJECT (aj_capteur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (aj_capteur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (aj_capteur, image15, "image15");
  GLADE_HOOKUP_OBJECT (aj_capteur, label40, "label40");
  GLADE_HOOKUP_OBJECT (aj_capteur, label41, "label41");

  return aj_capteur;
}

GtkWidget*
create_modifier_cap (void)
{
  GtkWidget *modifier_cap;
  GtkWidget *fixed3;
  GtkObject *mod1_adj;
  GtkWidget *mod1;
  GtkWidget *retour2;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label37;
  GtkWidget *label9;
  GtkWidget *check_id;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;
  GtkWidget *label42;
  GtkWidget *mod6;
  GtkWidget *label44;
  GtkWidget *label47;
  GtkWidget *label45;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *modA;
  GSList *modA_group = NULL;
  GtkWidget *modB;
  GtkWidget *modC;
  GtkWidget *label48;
  GtkWidget *mod5;
  GtkWidget *mod2;
  GtkWidget *mod3;
  GtkWidget *label46;
  GtkWidget *mod4;
  GtkWidget *mod7;
  GtkWidget *button_mod;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label36;

  modifier_cap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_cap), _("Modification d un capteur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_cap), fixed3);

  mod1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mod1 = gtk_spin_button_new (GTK_ADJUSTMENT (mod1_adj), 1, 0);
  gtk_widget_show (mod1);
  gtk_fixed_put (GTK_FIXED (fixed3), mod1, 296, 152);
  gtk_widget_set_size_request (mod1, 60, 27);

  retour2 = gtk_button_new ();
  gtk_widget_show (retour2);
  gtk_fixed_put (GTK_FIXED (fixed3), retour2, 64, 584);
  gtk_widget_set_size_request (retour2, 96, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (retour2), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">Retour</span></b>"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label9 = gtk_label_new (_("<b><span color=\"Darkblue\">ID:</span></b>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 208, 160);
  gtk_widget_set_size_request (label9, 48, 17);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  check_id = gtk_button_new ();
  gtk_widget_show (check_id);
  gtk_fixed_put (GTK_FIXED (fixed3), check_id, 408, 152);
  gtk_widget_set_size_request (check_id, 96, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (check_id), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("<b><span color=\"purple\">Verifier</span></b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label42 = gtk_label_new (_("<b><span color=\"Darkgreen\">Modification d'un capteur</span></b>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed3), label42, 208, 56);
  gtk_widget_set_size_request (label42, 224, 33);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  mod6 = gtk_entry_new ();
  gtk_widget_show (mod6);
  gtk_fixed_put (GTK_FIXED (fixed3), mod6, 176, 392);
  gtk_widget_set_size_request (mod6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod6), 8226);

  label44 = gtk_label_new ("");
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed3), label44, 104, 232);
  gtk_widget_set_size_request (label44, 49, 17);

  label47 = gtk_label_new (_("<b><span color=\"Darkblue\">Annee:</span></b>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed3), label47, 376, 216);
  gtk_widget_set_size_request (label47, 64, 17);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label45 = gtk_label_new (_("<b><span color=\"Darkblue\">Jour:</span></b>"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed3), label45, 88, 216);
  gtk_widget_set_size_request (label45, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  label12 = gtk_label_new (_("<b><span color=\"Darkblue\">Valeur:</span></b>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 88, 456);
  gtk_widget_set_size_request (label12, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label11 = gtk_label_new (_("<b><span color=\"Darkblue\">Etage:</span></b>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 88, 392);
  gtk_widget_set_size_request (label11, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label10 = gtk_label_new (_("<b><span color=\"Darkblue\">Type:</span></b>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 88, 328);
  gtk_widget_set_size_request (label10, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  modA = gtk_radio_button_new_with_mnemonic (NULL, _("Debit"));
  gtk_widget_show (modA);
  gtk_fixed_put (GTK_FIXED (fixed3), modA, 184, 328);
  gtk_widget_set_size_request (modA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modA), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modA));

  modB = gtk_radio_button_new_with_mnemonic (NULL, _("Dechet"));
  gtk_widget_show (modB);
  gtk_fixed_put (GTK_FIXED (fixed3), modB, 304, 328);
  gtk_widget_set_size_request (modB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modB), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modB));

  modC = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (modC);
  gtk_fixed_put (GTK_FIXED (fixed3), modC, 424, 328);
  gtk_widget_set_size_request (modC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modC), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modC));

  label48 = gtk_label_new (_("<b><span color=\"Darkblue\">Heure:</span></b>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed3), label48, 88, 280);
  gtk_widget_set_size_request (label48, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  mod5 = gtk_entry_new ();
  gtk_widget_show (mod5);
  gtk_fixed_put (GTK_FIXED (fixed3), mod5, 168, 280);
  gtk_widget_set_size_request (mod5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod5), 8226);

  mod2 = gtk_entry_new ();
  gtk_widget_show (mod2);
  gtk_fixed_put (GTK_FIXED (fixed3), mod2, 144, 208);
  gtk_widget_set_size_request (mod2, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod2), 8226);

  mod3 = gtk_entry_new ();
  gtk_widget_show (mod3);
  gtk_fixed_put (GTK_FIXED (fixed3), mod3, 296, 208);
  gtk_widget_set_size_request (mod3, 64, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod3), 8226);

  label46 = gtk_label_new (_("<b><span color=\"Darkblue\">Mois:</span></b>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed3), label46, 224, 216);
  gtk_widget_set_size_request (label46, 64, 17);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  mod4 = gtk_entry_new ();
  gtk_widget_show (mod4);
  gtk_fixed_put (GTK_FIXED (fixed3), mod4, 440, 208);
  gtk_widget_set_size_request (mod4, 88, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod4), 8226);

  mod7 = gtk_entry_new ();
  gtk_widget_show (mod7);
  gtk_fixed_put (GTK_FIXED (fixed3), mod7, 176, 456);
  gtk_widget_set_size_request (mod7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod7), 8226);

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed3), button_mod, 288, 528);
  gtk_widget_set_size_request (button_mod, 104, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Modifier</span></b>"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  g_signal_connect ((gpointer) retour2, "clicked",
                    G_CALLBACK (on_retour2_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_id, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_cap, modifier_cap, "modifier_cap");
  GLADE_HOOKUP_OBJECT (modifier_cap, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod1, "mod1");
  GLADE_HOOKUP_OBJECT (modifier_cap, retour2, "retour2");
  GLADE_HOOKUP_OBJECT (modifier_cap, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_cap, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier_cap, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_cap, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifier_cap, label9, "label9");
  GLADE_HOOKUP_OBJECT (modifier_cap, check_id, "check_id");
  GLADE_HOOKUP_OBJECT (modifier_cap, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (modifier_cap, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (modifier_cap, image4, "image4");
  GLADE_HOOKUP_OBJECT (modifier_cap, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_cap, label42, "label42");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod6, "mod6");
  GLADE_HOOKUP_OBJECT (modifier_cap, label44, "label44");
  GLADE_HOOKUP_OBJECT (modifier_cap, label47, "label47");
  GLADE_HOOKUP_OBJECT (modifier_cap, label45, "label45");
  GLADE_HOOKUP_OBJECT (modifier_cap, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier_cap, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier_cap, label10, "label10");
  GLADE_HOOKUP_OBJECT (modifier_cap, modA, "modA");
  GLADE_HOOKUP_OBJECT (modifier_cap, modB, "modB");
  GLADE_HOOKUP_OBJECT (modifier_cap, modC, "modC");
  GLADE_HOOKUP_OBJECT (modifier_cap, label48, "label48");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod5, "mod5");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod2, "mod2");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod3, "mod3");
  GLADE_HOOKUP_OBJECT (modifier_cap, label46, "label46");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod4, "mod4");
  GLADE_HOOKUP_OBJECT (modifier_cap, mod7, "mod7");
  GLADE_HOOKUP_OBJECT (modifier_cap, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (modifier_cap, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modifier_cap, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier_cap, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier_cap, label36, "label36");

  return modifier_cap;
}

GtkWidget*
create_recherche_cap (void)
{
  GtkWidget *recherche_cap;
  GtkWidget *fixed4;
  GtkWidget *retour3;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label38;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label17;
  GtkWidget *r4;
  GtkWidget *r2;
  GtkWidget *label18;
  GtkWidget *r5;
  GtkWidget *r3;
  GtkWidget *label16;
  GtkWidget *chercher_cap;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label29;
  GtkWidget *label43;
  GtkObject *r1_adj;
  GtkWidget *r1;
  GtkWidget *r8;
  GtkWidget *label22;
  GtkWidget *r7;

  recherche_cap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (recherche_cap), _("chercher un cateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (recherche_cap), fixed4);

  retour3 = gtk_button_new ();
  gtk_widget_show (retour3);
  gtk_fixed_put (GTK_FIXED (fixed4), retour3, 72, 528);
  gtk_widget_set_size_request (retour3, 104, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (retour3), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("<b><span color=\"Red\">Retour</span></b>"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox13), label38, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label20 = gtk_label_new (_("<b><span color=\"green\">Etage:</span></b>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 376, 384);
  gtk_widget_set_size_request (label20, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label19 = gtk_label_new (_("<b><span color=\"green\">Type:</span></b>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 128, 384);
  gtk_widget_set_size_request (label19, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label17 = gtk_label_new (_("<b><span color=\"green\">Date:</span></b>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 128, 272);
  gtk_widget_set_size_request (label17, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  r4 = gtk_label_new ("");
  gtk_widget_show (r4);
  gtk_fixed_put (GTK_FIXED (fixed4), r4, 200, 384);
  gtk_widget_set_size_request (r4, 136, 17);

  r2 = gtk_label_new ("");
  gtk_widget_show (r2);
  gtk_fixed_put (GTK_FIXED (fixed4), r2, 200, 272);
  gtk_widget_set_size_request (r2, 128, 17);

  label18 = gtk_label_new (_("<b><span color=\"green\">Heure:</span></b>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 368, 272);
  gtk_widget_set_size_request (label18, 56, 17);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  r5 = gtk_label_new ("");
  gtk_widget_show (r5);
  gtk_fixed_put (GTK_FIXED (fixed4), r5, 448, 384);
  gtk_widget_set_size_request (r5, 152, 17);

  r3 = gtk_label_new ("");
  gtk_widget_show (r3);
  gtk_fixed_put (GTK_FIXED (fixed4), r3, 448, 272);
  gtk_widget_set_size_request (r3, 144, 17);

  label16 = gtk_label_new (_("ID:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 176, 160);
  gtk_widget_set_size_request (label16, 49, 17);

  chercher_cap = gtk_button_new ();
  gtk_widget_show (chercher_cap);
  gtk_fixed_put (GTK_FIXED (fixed4), chercher_cap, 432, 160);
  gtk_widget_set_size_request (chercher_cap, 112, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (chercher_cap), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("<b><span color=\"darkblue\">Rechercher</span></b>"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox5), label29, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label43 = gtk_label_new (_("<b><span color=\"Black\">Rechercher un capteur</span></b>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed4), label43, 216, 48);
  gtk_widget_set_size_request (label43, 224, 33);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  r1_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  r1 = gtk_spin_button_new (GTK_ADJUSTMENT (r1_adj), 1, 0);
  gtk_widget_show (r1);
  gtk_fixed_put (GTK_FIXED (fixed4), r1, 272, 152);
  gtk_widget_set_size_request (r1, 88, 24);

  r8 = gtk_label_new ("");
  gtk_widget_show (r8);
  gtk_fixed_put (GTK_FIXED (fixed4), r8, 200, 200);
  gtk_widget_set_size_request (r8, 256, 25);

  label22 = gtk_label_new (_("<b><span color=\"green\">Valeur:</span></b>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 208, 456);
  gtk_widget_set_size_request (label22, 57, 16);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  r7 = gtk_label_new ("");
  gtk_widget_show (r7);
  gtk_fixed_put (GTK_FIXED (fixed4), r7, 296, 456);
  gtk_widget_set_size_request (r7, 144, 17);

  g_signal_connect ((gpointer) retour3, "clicked",
                    G_CALLBACK (on_retour3_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher_cap, "clicked",
                    G_CALLBACK (on_chercher_cap_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche_cap, recherche_cap, "recherche_cap");
  GLADE_HOOKUP_OBJECT (recherche_cap, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (recherche_cap, retour3, "retour3");
  GLADE_HOOKUP_OBJECT (recherche_cap, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (recherche_cap, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (recherche_cap, image13, "image13");
  GLADE_HOOKUP_OBJECT (recherche_cap, label38, "label38");
  GLADE_HOOKUP_OBJECT (recherche_cap, label20, "label20");
  GLADE_HOOKUP_OBJECT (recherche_cap, label19, "label19");
  GLADE_HOOKUP_OBJECT (recherche_cap, label17, "label17");
  GLADE_HOOKUP_OBJECT (recherche_cap, r4, "r4");
  GLADE_HOOKUP_OBJECT (recherche_cap, r2, "r2");
  GLADE_HOOKUP_OBJECT (recherche_cap, label18, "label18");
  GLADE_HOOKUP_OBJECT (recherche_cap, r5, "r5");
  GLADE_HOOKUP_OBJECT (recherche_cap, r3, "r3");
  GLADE_HOOKUP_OBJECT (recherche_cap, label16, "label16");
  GLADE_HOOKUP_OBJECT (recherche_cap, chercher_cap, "chercher_cap");
  GLADE_HOOKUP_OBJECT (recherche_cap, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (recherche_cap, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (recherche_cap, image5, "image5");
  GLADE_HOOKUP_OBJECT (recherche_cap, label29, "label29");
  GLADE_HOOKUP_OBJECT (recherche_cap, label43, "label43");
  GLADE_HOOKUP_OBJECT (recherche_cap, r1, "r1");
  GLADE_HOOKUP_OBJECT (recherche_cap, r8, "r8");
  GLADE_HOOKUP_OBJECT (recherche_cap, label22, "label22");
  GLADE_HOOKUP_OBJECT (recherche_cap, r7, "r7");

  return recherche_cap;
}

GtkWidget*
create_Defectueux (void)
{
  GtkWidget *Defectueux;
  GtkWidget *fixed5;
  GtkWidget *label49;
  GtkWidget *treeview_defectueux;
  GtkWidget *refrech_def;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image19;
  GtkWidget *label50;
  GtkWidget *retour4;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image20;
  GtkWidget *label51;

  Defectueux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Defectueux), _("Capteurs defectueux"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Defectueux), fixed5);

  label49 = gtk_label_new (_("<b><span color=\"red\">Capteurs defectueux</span></b>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 232, 40);
  gtk_widget_set_size_request (label49, 264, 41);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  treeview_defectueux = gtk_tree_view_new ();
  gtk_widget_show (treeview_defectueux);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview_defectueux, 144, 136);
  gtk_widget_set_size_request (treeview_defectueux, 456, 216);

  refrech_def = gtk_button_new ();
  gtk_widget_show (refrech_def);
  gtk_fixed_put (GTK_FIXED (fixed5), refrech_def, 280, 400);
  gtk_widget_set_size_request (refrech_def, 136, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (refrech_def), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image19 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox16), image19, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("<b><span color=\"lightblue\">Refresh</span></b>"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox16), label50, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  retour4 = gtk_button_new ();
  gtk_widget_show (retour4);
  gtk_fixed_put (GTK_FIXED (fixed5), retour4, 72, 512);
  gtk_widget_set_size_request (retour4, 112, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (retour4), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox17), image20, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("<b><span color=\"orange\">Retour</span></b>"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox17), label51, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  g_signal_connect ((gpointer) treeview_defectueux, "row_activated",
                    G_CALLBACK (on_treeview_defectueux_row_activated),
                    NULL);
  g_signal_connect ((gpointer) refrech_def, "clicked",
                    G_CALLBACK (on_refrech_def_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour4, "clicked",
                    G_CALLBACK (on_retour4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Defectueux, Defectueux, "Defectueux");
  GLADE_HOOKUP_OBJECT (Defectueux, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Defectueux, label49, "label49");
  GLADE_HOOKUP_OBJECT (Defectueux, treeview_defectueux, "treeview_defectueux");
  GLADE_HOOKUP_OBJECT (Defectueux, refrech_def, "refrech_def");
  GLADE_HOOKUP_OBJECT (Defectueux, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Defectueux, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Defectueux, image19, "image19");
  GLADE_HOOKUP_OBJECT (Defectueux, label50, "label50");
  GLADE_HOOKUP_OBJECT (Defectueux, retour4, "retour4");
  GLADE_HOOKUP_OBJECT (Defectueux, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Defectueux, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Defectueux, image20, "image20");
  GLADE_HOOKUP_OBJECT (Defectueux, label51, "label51");

  return Defectueux;
}

GtkWidget*
create_affichage_cap1 (void)
{
  GtkWidget *affichage_cap1;
  GtkWidget *fixed6;
  GtkWidget *treeview_capteur1;
  GtkWidget *label52;
  GtkWidget *refresh_capteur;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image21;
  GtkWidget *label53;

  affichage_cap1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage_cap1), _("afficher les capteurs"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (affichage_cap1), fixed6);

  treeview_capteur1 = gtk_tree_view_new ();
  gtk_widget_show (treeview_capteur1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_capteur1, 64, 128);
  gtk_widget_set_size_request (treeview_capteur1, 584, 232);

  label52 = gtk_label_new_with_mnemonic (_("<b><span color=\"Green\">La liste des capteurs</span></b>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed6), label52, 144, 40);
  gtk_widget_set_size_request (label52, 376, 33);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  refresh_capteur = gtk_button_new ();
  gtk_widget_show (refresh_capteur);
  gtk_fixed_put (GTK_FIXED (fixed6), refresh_capteur, 272, 392);
  gtk_widget_set_size_request (refresh_capteur, 120, 45);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (refresh_capteur), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image21 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox18), image21, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox18), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_capteur1, "row_activated",
                    G_CALLBACK (on_treeview_capteur1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) refresh_capteur, "clicked",
                    G_CALLBACK (on_refresh_capteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage_cap1, affichage_cap1, "affichage_cap1");
  GLADE_HOOKUP_OBJECT (affichage_cap1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (affichage_cap1, treeview_capteur1, "treeview_capteur1");
  GLADE_HOOKUP_OBJECT (affichage_cap1, label52, "label52");
  GLADE_HOOKUP_OBJECT (affichage_cap1, refresh_capteur, "refresh_capteur");
  GLADE_HOOKUP_OBJECT (affichage_cap1, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (affichage_cap1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (affichage_cap1, image21, "image21");
  GLADE_HOOKUP_OBJECT (affichage_cap1, label53, "label53");

  return affichage_cap1;
}

