/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_capteur (void);
GtkWidget* create_aj_capteur (void);
GtkWidget* create_modifier_cap (void);
GtkWidget* create_recherche_cap (void);
GtkWidget* create_Defectueux (void);
GtkWidget* create_affichage_cap1 (void);
